// <auto-generated />
namespace FPT_Learning_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecoursefk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecoursefk));
        
        string IMigrationMetadata.Id
        {
            get { return "202108270822053_update course fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
